# Generated by Django 2.2.6 on 2019-10-20 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newspaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_paper_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='readers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readers', models.CharField(max_length=100)),
                ('newspaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OneToManyApp.Newspaper')),
            ],
        ),
    ]
